#ifndef TASK_CONSTANTS_H
#define TASK_CONSTANTS_H

struct TaskConstants {
    const int TASK_TYPE_SINGLE_RUN = 0;
    const int TASK_TYPE_CYCLIC = 1;
    const int TASK_TYPE_REACTIVE = 2;

    const int TASK_STATE_UNDEFINED = 0;
    const int TASK_STATE_RUNNING = 1;
    const int TASK_STATE_AWAITS_IN_QUEUE = 2;
    const int TASK_STATE_AWAINTS_NOTIFICATION = 3;
    const int TASK_STATE_SUSPENDED = 4;
    const int TASK_STATE_DELETED = 5;

    const int HANDLER_GC_INTERVAL = 60000;
    const int HANDLER_HOLDER_SIZE = 30;
    const int HANDLER_ACTIVE_CORE = 1;

    const int PRIOTITY_NOW = 32;
    const int PRIOTITY_HIGH = 16;
    const int PRIOTITY_MIDDLE = 8;
    const int PRIOTITY_LOW = 0;

    const int PORT_HANDLER_STATE_COLLECTOR_TASK_STACK_SIZE = 2048;
    const int PORT_HANDLER_STATE_COLLECTOR_TASK_PRIORITY = PRIOTITY_HIGH;

    const int PORT_HANDLER_STATEFUL_COLLECTOR_TASK_STACK_SIZE = 2048;
    const int PORT_HANDLER_STATEFUL_COLLECTOR_TASK_DELAY = 10;
    const int PORT_HANDLER_STATEFUL_COLLECTOR_TASK_PRIORITY = PRIOTITY_NOW;

    const int INTERNAL_STORAGE_TASK_STACK_SIZE = 2048;
    const int INTERNAL_STORAGE_TASK_DELAY = 60000;
    const int INTERNAL_STORAGE_TASK_PRIORITY = PRIOTITY_MIDDLE;
};

#endif